version: '2.3'
services:
  db:
    image: postgres:12.2
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./scripts/chronicleSetup.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=test
    ports:
      - "5432:5432"
    healthcheck:
      test: "pg_isready -U test -d test"
      interval: 10s
      timeout: 5s
      retries: 5
  api:
    build: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      - sender_email=
      - sender_password=
      - DB_HOST=db
      - DB_USERNAME=test
      - DB_NAME=test
      - DB_PASSWORD=test
    networks:
      - default
    ports:
      - "5000:5000"
    links:
      - db
    restart: always